<?php

use Illuminate\Database\Seeder;

class ObiskTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('obisk')->delete();
        
        \DB::table('obisk')->insert(array (
            0 => 
            array (
                'sifra_obisk' => 1,
                'sifra_dn' => 1,
                'sifra_plan' => 1,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-08',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            1 => 
            array (
                'sifra_obisk' => 2,
                'sifra_dn' => 1,
                'sifra_plan' => 2,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-09',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            2 => 
            array (
                'sifra_obisk' => 3,
                'sifra_dn' => 1,
                'sifra_plan' => 3,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-12',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            3 => 
            array (
                'sifra_obisk' => 4,
                'sifra_dn' => 1,
                'sifra_plan' => 4,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-14',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            4 => 
            array (
                'sifra_obisk' => 5,
                'sifra_dn' => 2,
                'sifra_plan' => 5,
                'originalna_sifra_plan' => 5,
                'sifra_ps' => 45331,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-08',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            5 => 
            array (
                'sifra_obisk' => 6,
                'sifra_dn' => 2,
                'sifra_plan' => 6,
                'originalna_sifra_plan' => 6,
                'sifra_ps' => 45331,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-09',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            6 => 
            array (
                'sifra_obisk' => 7,
                'sifra_dn' => 3,
                'sifra_plan' => 7,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 21245,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-09',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            7 => 
            array (
                'sifra_obisk' => 8,
                'sifra_dn' => 3,
                'sifra_plan' => 8,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 21245,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-13',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            8 => 
            array (
                'sifra_obisk' => 9,
                'sifra_dn' => 3,
                'sifra_plan' => 9,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 21245,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-16',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            9 => 
            array (
                'sifra_obisk' => 10,
                'sifra_dn' => 4,
                'sifra_plan' => 10,
                'originalna_sifra_plan' => 10,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-09',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            10 => 
            array (
                'sifra_obisk' => 11,
                'sifra_dn' => 4,
                'sifra_plan' => 11,
                'originalna_sifra_plan' => 11,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-12',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            11 => 
            array (
                'sifra_obisk' => 12,
                'sifra_dn' => 4,
                'sifra_plan' => 12,
                'originalna_sifra_plan' => 12,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-14',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            12 => 
            array (
                'sifra_obisk' => 13,
                'sifra_dn' => 5,
                'sifra_plan' => 11,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-12',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            13 => 
            array (
                'sifra_obisk' => 14,
                'sifra_dn' => 5,
                'sifra_plan' => 13,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-15',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            14 => 
            array (
                'sifra_obisk' => 15,
                'sifra_dn' => 5,
                'sifra_plan' => 14,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-19',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            15 => 
            array (
                'sifra_obisk' => 16,
                'sifra_dn' => 6,
                'sifra_plan' => 15,
                'originalna_sifra_plan' => 15,
                'sifra_ps' => 21245,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-20',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            16 => 
            array (
                'sifra_obisk' => 17,
                'sifra_dn' => 7,
                'sifra_plan' => 16,
                'originalna_sifra_plan' => 16,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-26',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            17 => 
            array (
                'sifra_obisk' => 18,
                'sifra_dn' => 7,
                'sifra_plan' => 17,
                'originalna_sifra_plan' => 17,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-30',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            18 => 
            array (
                'sifra_obisk' => 19,
                'sifra_dn' => 8,
                'sifra_plan' => 18,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 45331,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-27',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            19 => 
            array (
                'sifra_obisk' => 20,
                'sifra_dn' => 8,
                'sifra_plan' => 19,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 45331,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-30',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            20 => 
            array (
                'sifra_obisk' => 21,
                'sifra_dn' => 9,
                'sifra_plan' => 20,
                'originalna_sifra_plan' => 20,
                'sifra_ps' => 21245,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-07-04',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            21 => 
            array (
                'sifra_obisk' => 22,
                'sifra_dn' => 9,
                'sifra_plan' => 21,
                'originalna_sifra_plan' => 21,
                'sifra_ps' => 21245,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-07-11',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            22 => 
            array (
                'sifra_obisk' => 23,
                'sifra_dn' => 10,
                'sifra_plan' => 22,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-16',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            23 => 
            array (
                'sifra_obisk' => 24,
                'sifra_dn' => 10,
                'sifra_plan' => 23,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-20',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            24 => 
            array (
                'sifra_obisk' => 25,
                'sifra_dn' => 10,
                'sifra_plan' => 24,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-23',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            25 => 
            array (
                'sifra_obisk' => 26,
                'sifra_dn' => 11,
                'sifra_plan' => 25,
                'originalna_sifra_plan' => 25,
                'sifra_ps' => 45331,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-07-13',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            26 => 
            array (
                'sifra_obisk' => 27,
                'sifra_dn' => 12,
                'sifra_plan' => 3,
                'originalna_sifra_plan' => 3,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-12',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            27 => 
            array (
                'sifra_obisk' => 28,
                'sifra_dn' => 13,
                'sifra_plan' => 26,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 45331,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-01',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            28 => 
            array (
                'sifra_obisk' => 29,
                'sifra_dn' => 13,
                'sifra_plan' => 27,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 45331,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-02',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            29 => 
            array (
                'sifra_obisk' => 30,
                'sifra_dn' => 13,
                'sifra_plan' => 27,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 45331,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-02',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            30 => 
            array (
                'sifra_obisk' => 31,
                'sifra_dn' => 14,
                'sifra_plan' => 28,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-01',
                'datum_opravljenosti_obiska' => '2017-06-01',
                'opravljen' => 1,
                'nadomescanje' => 0,
            ),
            31 => 
            array (
                'sifra_obisk' => 32,
                'sifra_dn' => 14,
                'sifra_plan' => 29,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-05',
                'datum_opravljenosti_obiska' => '2017-06-05',
                'opravljen' => 1,
                'nadomescanje' => 0,
            ),
            32 => 
            array (
                'sifra_obisk' => 33,
                'sifra_dn' => 14,
                'sifra_plan' => 30,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-07',
                'datum_opravljenosti_obiska' => '2017-06-07',
                'opravljen' => 1,
                'nadomescanje' => 0,
            ),
            33 => 
            array (
                'sifra_obisk' => 34,
                'sifra_dn' => 15,
                'sifra_plan' => 31,
                'originalna_sifra_plan' => 31,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-05',
                'datum_opravljenosti_obiska' => '2017-06-05',
                'opravljen' => 1,
                'nadomescanje' => 0,
            ),
            34 => 
            array (
                'sifra_obisk' => 35,
                'sifra_dn' => 15,
                'sifra_plan' => 32,
                'originalna_sifra_plan' => 32,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-07',
                'datum_opravljenosti_obiska' => '2017-06-07',
                'opravljen' => 1,
                'nadomescanje' => 0,
            ),
            35 => 
            array (
                'sifra_obisk' => 36,
                'sifra_dn' => 15,
                'sifra_plan' => 2,
                'originalna_sifra_plan' => 2,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-09',
                'datum_opravljenosti_obiska' => NULL,
                'opravljen' => 0,
                'nadomescanje' => 0,
            ),
            36 => 
            array (
                'sifra_obisk' => 37,
                'sifra_dn' => 16,
                'sifra_plan' => 33,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-01',
                'datum_opravljenosti_obiska' => '2017-06-01',
                'opravljen' => 1,
                'nadomescanje' => 0,
            ),
            37 => 
            array (
                'sifra_obisk' => 38,
                'sifra_dn' => 16,
                'sifra_plan' => 34,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-02',
                'datum_opravljenosti_obiska' => '2017-06-02',
                'opravljen' => 1,
                'nadomescanje' => 0,
            ),
            38 => 
            array (
                'sifra_obisk' => 39,
                'sifra_dn' => 16,
                'sifra_plan' => 35,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-02',
                'datum_opravljenosti_obiska' => '2017-06-03',
                'opravljen' => 1,
                'nadomescanje' => 0,
            ),
            39 => 
            array (
                'sifra_obisk' => 40,
                'sifra_dn' => 16,
                'sifra_plan' => 31,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 83312,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-05',
                'datum_opravljenosti_obiska' => '2017-06-05',
                'opravljen' => 1,
                'nadomescanje' => 0,
            ),
            40 => 
            array (
                'sifra_obisk' => 41,
                'sifra_dn' => 17,
                'sifra_plan' => 36,
                'originalna_sifra_plan' => 36,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-02',
                'datum_opravljenosti_obiska' => '2017-06-02',
                'opravljen' => 1,
                'nadomescanje' => 0,
            ),
            41 => 
            array (
                'sifra_obisk' => 42,
                'sifra_dn' => 18,
                'sifra_plan' => 36,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-06-02',
                'datum_opravljenosti_obiska' => '2017-06-02',
                'opravljen' => 1,
                'nadomescanje' => 0,
            ),
            42 => 
            array (
                'sifra_obisk' => 43,
                'sifra_dn' => 19,
                'sifra_plan' => 37,
                'originalna_sifra_plan' => -1,
                'sifra_ps' => 12234,
                'sifra_nadomestne_ps' => NULL,
                'datum_obiska' => '2017-05-31',
                'datum_opravljenosti_obiska' => '2017-05-31',
                'opravljen' => 1,
                'nadomescanje' => 0,
            ),
        ));
        
        
    }
}